### ISSUE TITLE
NotImplementedException

### ISSUE THREAD

**Issue by ghost** [Realm-of-Everlasting-Code/C-Sharp#1]
<img width="354" alt="1" src="https://user-images.githubusercontent.com/8431682/70553857-43772d80-1b7c-11ea-87d1-ebf54d00bc01.png">

An exception of Type 'GitHubException' occurred: "The expected resources are not implemented".

Inner Exception: 'NotImplementedException'

StackTrace: Run(): Kai.cs at line 20;
CallRun(): RealmOfEverlastingCodeChannel.cs at line 2307;
CallCallRun(): CSharpInn.cs at line 400;
CallCallCallRun(): Discord.cs at line -500;

While handling of the above exception another exception occurred:

An Exception of Type JemmaCustomException occurred: "God damn it, I'm getting too old for this".

Inner Exception: 'IndexOutOfRangeException': 'Line numbers may not be negative.'

StackTrace: [external code] (Jemma.exe)

**Comment by Almantask** [comment]
@AntipodeYarns please resolve 🙂

**Comment by AntipodeYarns** [comment]
Harsh. But fair.

Regards

Jemma Hooper

________________________________

**Comment by ghost** [comment]
Well, let's see where this goes...
